### ISSUE TITLE
Introduction to decentralized pattern library

### ISSUE THREAD

**Issue by okdistribute** [HerbCaudill/taco#3]
Thanks so much for making such a concise and well-defined library for a problem that many p2p and local-first applications will face. What are you using it for? Or is it a hobby project?

I've been working on a decentralized pattern library called [Decentralization, off the shelf](https://decentpatterns.xyz) with [Simply Secure](https://simplysecure.com). We're currently working on a set of patterns and an introductory handbook for different ways identity can be done in decentralized applications. I'm focusing particularly on researching sets of pros and cons, and where particular libraries may be well suited for particular use cases (or not). I'm working on all this in the [github repository](https://github.com/simplysecure/dots-patterns/), see [disposible identity](https://github.com/simplysecure/dots-patterns/blob/master/patterns/disposable-identity.md) for an early-stage example.

I'd like to include taco and some of it's ideas, perhaps even creating a pattern for 'trust on first use' ... I'd also love to hear how you imagine this being used in applications and which kinds of applications it would be great for (and what are the pitfalls of this approach, as well)! Do you have any time to give more thoughts on broader applications of taco?

**Comment by HerbCaudill** [comment]
Hi, Karissa - sorry for the silence, I just saw this! 

The dots-patterns repo is a terrific idea, looks like you're off to a great start! Please feel free to list anything that seems useful from taco. 

My motivation: I'm trying to figure out the local-first space for a couple of different hypothetical future products. I've been working on [Cevitxe](https://github.com/DevResults/cevitxe), a wrapper for [Automerge](http://github.com/automerge/automerge) that makes it easier to add CRDT-powered peer-to-peer collaboration to a web app. Taco is a side quest that I've been on for a few months now to provide group management, authentication and authorization to Cevitxe. 

I'd be happy to talk about the broader local-first landscape - please DM me on Twitter (@herbcaudill) if you'd like to set up a time to talk.

P.S. 'trust on first use (TOFU)' isn't my idea; 'trust after confirmation of identity (TACO)' is my made-up name for this implementation, but the idea is stolen from Keybase's invitation protocol (see [Seitan Tokens](https://book.keybase.io/docs/teams/seitan)). I think TOFU is more than adequate for most people, but under the right circumstances it could provide an opening for a determined adversary. The Seitan protocol eliminates that opening without complicating the user experience.
